config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'normalizer#index'

  scope :normalizer do
    post 'upload' => 'normalizer#upload'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/normalizer_controller.rb
# frozen_string_literal: true
class NormalizerController < ApplicationController
  # POST /upload
  def upload
    file = normalizer_params[:file]
    file_ext = file.original_filename.split('.').last

    xlsx = Roo::Spreadsheet.open(file.path, extension: file_ext)

    addresses = []

    xlsx.sheet(0).each do |row|
      addresses << row[0]
    end

    geocoded_rows = geocode_addresses(addresses)
    create_and_send_xlsx(geocoded_rows)
  end

  private

  def normalizer_params
    params.permit(:file)
  end

  def geocode_addresses(addresses)
    rows_results = []

    # We will use a maximum of addresses/rows
    addresses = addresses.first(500)

    addresses.each_with_index do |address, index|
      # Geocoder could fail if the google requests limit is exceeded
      # so we redo the requests until google is able to geocode
      logger.info "ADDRESS #{index}: #{address}"

      begin
        coords = Geocoder.coordinates(address)

        row =
          if coords.nil?
            [address, nil, nil]
          else
            [address] + coords
          end

        rows_results << row
      rescue => error
        logger.info error.inspect
        redo
      end
    end

    rows_results
  end

  def create_and_send_xlsx(rows)
    package = Axlsx::Package.new
    workbook = package.workbook

    workbook.add_worksheet(name: 'Sheet1') do |sheet|
      rows.each do |row|
        sheet.add_row row
      end
    end

    filename = SecureRandom.hex

    package.serialize("tmp/#{filename}.xlsx")

    send_data(File.open("tmp/#{filename}.xlsx").read, filename: 'Coordenadas.xlsx')

    File.delete("tmp/#{filename}.xlsx")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def generateExcel(filename)
		file = Spreadsheet.open "#{filename}"
		(0..file.worksheet(0).last_row_index).to_a.each do |iter|
			coords = Geocoder.coordinates(file.worksheet(0).cell(iter,0))
			!coords.nil? ? file.worksheet(0).insert_row(iter,[file.worksheet(0).cell(iter,0), coords[0], coords[1]]) : file.worksheet(0).insert_row(iter,[file.worksheet(0).cell(iter,0), "", ""])
		end
		outname = Digest::SHA256.hexdigest(Time.now.to_s + rand(100).to_s)
		file.write("#{outname}.xls")
		"#{outname}.xls"
	end

end

app/helpers/normalizer_helper.rb
module NormalizerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Normalizer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/normalizer/index.html.erb
<div class="jumbotron">
	<h2>Sistema de Georeferenciación de Direcciones</h2>
	<p class="lead">
		Se debe subir un archivo xlsx o xls con la lista de direcciones en la primera columna. El archivo de salida será un xlsx con direcciones en la primera columna, las latitudes en la segunda columna y las longitudes en la tercera columna.
	</p>

	<%= form_tag upload_path, multipart: true do %>
		<div class="form-group">
			<%= label_tag 'file', 'Buscar Archivo' %>
			<%= file_field_tag 'file', class: 'form-control' %>
		</div>

	  <%= submit_tag 'Subir Archivo', class: 'btn btn-primary' %>
	<% end %>
</div>